# Generated by Django 5.2.6 on 2025-10-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_imagen_alter_producto_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='contraseña_hash',
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='password',
            field=models.CharField(default='placeholder', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
